/*
 * axis_scaler.h
 *
 *  Created on: 06.11.2025
 *      Author: mac
 */

#ifndef INF_ENG_EMLEARN_AXIS_SCALER_H_
#define INF_ENG_EMLEARN_AXIS_SCALER_H_


#pragma once
#include <stdint.h>

/* Autogenerated: axis-wise z-score on raw Ax,Ay,Az */
static const float AXIS_MEAN[3] = { -2.13214795, 1057.5138, -58.2942571 };
static const float AXIS_STD[3]  = { 176.231162, 277.850411, 233.24407 };



#endif /* INF_ENG_EMLEARN_AXIS_SCALER_H_ */
